CREATE TABLE GALLERY(
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    GALLERY VARCHAR(25) NOT NULL,
    TITLE VARCHAR(25) NOT NULL,
    FILEPATH VARCHAR(150) NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    PRIMARY KEY(ID)
) ENGINE=MYISAM COLLATE LATIN1_GENERAL_CS;
